# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Steve Ortiz
description: >
  Steve Ortiz has over 17 years of experience working as a software developer
  and team leader.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chesshacker.github.io" # the base hostname & protocol for your site
keywords: >
  chesshacker, steve, ortiz, rackspace, navair, software, developer, chess,
  texas a&m, tamu, pax, pax river, patuxent river, china lake, lexington park,
  maryland, ridgecrent, california, javascript, aws, node.js, portfolio
screenshot: https://s3-us-west-2.amazonaws.com/images.ortizaggies.com/website-snapshot.jpg
linkedin_username: chesshacker
github_username:  chesshacker
twitter_username: chesshacker
email: steve@ortizaggies.com

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
sass:
    style: :compressed
