# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Steve Ortiz
description: >
  Steve Ortiz has over 17 years of experience working as a software developer
  and team leader.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://steveortiz.github.io" # the base hostname & protocol for your site
keywords: >
  steveortiz, steve, ortiz, rackspace, navair, software, developer, chess,
  texas a&m, tamu, pax, pax river, patuxent river, china lake, lexington park,
  maryland, ridgecrent, california, javascript, aws, node.js, portfolio
screenshot: https://284f7e12378ae35fe21a-7e78ad4f897ae0179c6a991c235afb37.ssl.cf5.rackcdn.com/images/website-snapshot.jpg
linkedin_username: trustycoder
github_username:  steveortiz
twitter_username: trustycoder
email: steve@ortizaggies.com

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
sass:
    style: :compressed
