# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Steve Ortiz
email: steve@ortizaggies.com
description: >
  Professional online portfolio for Steve Ortiz
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://steveortiz.github.io" # the base hostname & protocol for your site
twitter_username: stevecancode
github_username:  steveortiz

# Build settings
markdown: kramdown
highlighter: pygments
